title: Cates
email: catiacneto@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Hi! I'm Cátia, a multidiciplinary designer. This is my website where you can learn a bit more about me and my work. Nice to meet you!
baseurl: /CN_ProjectoFinal
url: "" # the base hostname & protocol for your site, e.g. http://example.com
linkedin_username: catianeto
behance_username: catianeto

# Build settings
theme: minima
plugins:
  - jekyll-feed

# portfolio
collections:
  portfolio: 
    output: true
    permalink: /portfolio/:title:output_ext
    folder: _portfolio

  archive:
    output: true
    permalink: /portfolio/archive/:title:output_ext
    folder: _archive

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

